
insert into users(address,
	dob,
	email,
	firstName,
	lastName,
	gender,
	mobileno,
	password,	
	city,
	country,
	locality,
	cstate) values('second cross street',now(),'test@parack.com','','Chokkalingam','Male','94XXXXXXX4',
	'password','chennai','india','USA','tamilnadu');

insert into users(address,
	dob,
	email,
	firstName,
	lastName,
	gender,
	mobileno,
	password,	
	city,
	country,
	locality,
	cstate) values('second cross street',now(),'test2@parack.com','Shameer','Ahamed','Male','90XXXXXXX5',
	'password','chennai','india','USA','tamilnadu');

insert into users(address,
	dob,
	email,
	firstName,
	lastName,
	gender,
	mobileno,
	password,	
	city,
	country,
	locality,
	cstate) values('second cross street',now(),'test3@parack.com','Sakthivel','Rethinasamy','Male','99XXXXXXX5',
	'password','chennai','india','USA','tamilnadu');
	
	insert into users(address,
	dob,
	email,
	firstName,
	lastName,
	gender,
	mobileno,
	password,	
	city,
	country,
	locality,
	cstate) values('second cross street',now(),'test3@parack.com','Ramesh','Sakthivel','Male','99XXXXXXX9',
	'password','chennai','india','USA','tamilnadu');
	
	commit;